[workspace]
resolver = "2"
members = [
    "docstrings",
    "forc",
    "ir",
    "parser",
    "sway-core",
    "sway-fmt",
    "sway-server",
    "sway-types",
    "sway-utils",
    "test"
]

[profile.dev.package.sway-server]
debug = 2
